- project:
    templates:
      - openstack-lower-constraints-jobs
      - openstack-python3-victoria-jobs
      - check-requirements
      - openstack-cover-jobs
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py36
        - openstack-tox-py37
        - openstack-tox-py38
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py36
        - openstack-tox-py37
        - openstack-tox-py38
